app:
  domain: localhost:8088
  host: 0.0.0.0
  https: false
  port: 8088
  read_timeout: 1
  write_timeout: 2
  env: dev
domain:
  get_host: true
  url: localhost:9527
db:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  db_name: prado
  username: root
  password: root
  log_mode: info
  charset: utf8
  enable_file_log_writer: true
  log_filename: sql.log
redis:
  host: 127.0.0.1
  port: 6379
  password:
  db: 0
log:
  level: debug
  path: ./storage/logs
  filename: app.log
  format: json
  show_line: true
  max_backups: 3
  max_size: 500
  max_age: 3
  compress: true
  console_stdout: true
  file_stdout: true
  localtime: true
jwt:
  secret: prado
  timeout: 86400
file:
  save_dir: static/upload
mail:
  host: smtp.qq.com
  port: 465
  user:
  password:
  to: